deployments:
  default:
    filename:
      ./.squash/default/docker-compose.yml
    context_path:
      ./.squash/default
    always_build_images: yes
    vm_size: 1GB
  default-preconfigured:
    filename:
      ./.squash/pre-configured/docker-compose.yml
    context_path:
      ./.squash/pre-configured
    always_build_images: yes
    vm_size: 1GB
