deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    copy_files: /abcd ~/code
  branch:
    vm_size: 1
    vm_storage_gb: 13
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
  nodocker:
    squash_pr_comments: false
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
    pipelines:
      - default:
          group_id: api
          scripts:
            - echo true
      - secondary:
          group_id: app
          depends_on_group: api
          scripts:
            - ls -la
