deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    backend_wait: 20
    copy_files: /abcd ~/code
    subdomain_port_mapping:
      - test:81
      - test--test:81
      - another-test:8000
      - and--another-test:8000
  branch:
    vm_size: 1
    vm_storage_gb: 13
    ready_wait:
      120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    run_options: --env APM_SECRET_TOKEN=${APM_SECRET_TOKEN} APM_SERVER_URL=${APM_SERVER_URL} --restart always
    context_path: ./stuff
    subdomains:
      Awesome Name:
        - awesomedomain,/?que=99764QQ
      Awesomness x2:
         - subd,/abc
      Awesomness x3:
         - plain
  nodocker:
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    run_options: --env APM_SECRET_TOKEN=${APM_SECRET_TOKEN} APM_SERVER_URL=${APM_SERVER_URL}
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
