deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    copy_files: /abcd ~/code
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    squash_pr_comments: true    
  branch:
    vm_size: 1
    vm_storage_gb: 13
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
  nodocker:
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
