deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    copy_files: /abcd ~/code
    squash_pr_comments: true
  nodocker:
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
    squash-cmd--aws-credentials:
      aws_access_key: $ACCESS_KEY
      aws_secret_key: $SECRET_KEY
    pipelines:
      - s3:
          scripts:
            - mkdir user-pics
            - touch user-pics/filename
            - squash-cmd--aws-s3-upload:
                bucket: tfm-test-bucket
                region: us-east-1
                from_folder: user-pics
                is_download: true
                overwrite: true
                arguments: |
                 --quiet  \
                 --cache-control "max-age=11300"
