deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 20
    some_field: 123
    backend_wait: abc
    dc_skip_docker_build: false
    environment:
      - TEST_VAL=a42
      - SOMETHING=${SQUASH_BRANCH_WITH_ID}ABC
      - REGISTRY_PASSWORD=$REGISTRY_PASSWORD
      - ${SQUASH_BRANCH_WITH_ID}ABC=abcde
      - $TEST_VAL=test
      - TEST_VAL2=abcd!?#$&&_123
    copy_files: /${TEST_VAL}ABC ~/code
    auto_deploy_on_commits: true     adas
    squash_pr_comments: true   asd
    build_options: --build-arg SOMETHING=$SQUASH_BRANCH
    subdomain_port_mapping:
      - test:81
      - test--test:81
      - another-test:8000
      - and--another-test:8000
    deployment_page_commands:
      list something:
        - ls -la ./
        - sleep 40 && echo branch id is $SQUASH_BRANCH_WITH_ID
      echo awesome:
        - echo awesome
      echo target:
        stuff-service:
          - echo awesome
    pre_launch:
      - target: stuff-service
        command: exec
        options: "{target} bash -c 'ls -la ./'"
    post_launch:
      - target: stuff-service
        command: exec
        options: "{target} bash -c 'echo test && echo test > test'"
  /PI:
    vm_size: 1
    vm_storage_gb: 130
    deployment_type: docker
    environment:
      TEST_VAL=a42
    ready_wait:
      120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    build_options: --build-arg TEST_VAL2 --build-arg TEST_VAL
    run_options: --hostname ${SQUASH_BRANCH_WITH_ID} --env TEST_VAL2=$SQUASH_BRANCH_WITH_ID --restart always --env ${TEST_VAL}=test
    context_path: ./stuff
    subdomains:
      Awesome Name:
        - awesomedomain,/?que=99764QQ
      Awesomness x2:
         - subd,/abc
      Awesomness x3:
         - plain
    deployment_page_commands:
      list something:
        - ls -la ./
        - sleep 40 && echo branch id is $SQUASH_BRANCH_WITH_ID
  branchA:
    vm_size: 6
    environment:
      TEST_VAL=4242
    ready_wait:
      120
    filename:
      ./stuff/DockerfileA
    dockerfileonly: true
    build_options: --build-arg TEST_VAL --build-arg TEST_VAL2 
    run_options: --env TEST_VAL2=43 --env TEST_VAL3=$SQUASH_BRANCH_WITH_ID
    context_path: ./stuff
    pre_launch:
      - command: cp
        target: brancha
        docker: true
        options: ".ssh/id_rsa {target}:/test"
      - target: brancha
        command: exec
        docker: true
        options: -it {target} bash -c 'env > .env.local'
    post_launch:
      - command: exec
        target: brancha
        docker: true
        options: "-it {target} bash -c 'echo TEST_VAL is $TEST_VAL'"
  branch_B:
    vm_size: 1GB
    environment:
      TEST_VAL=424242
    ready_wait:
      120
    filename:
      ./stuff/DockerfileB
    dockerfileonly: true
    run_options: --env TEST_VAL2=$SQUASH_DOMAIN
    context_path: ./stuff
    pre_launch:
      - target: branchB
        command: exec
        docker: true
        options: -it {target} bash -c 'env > .env.local'
    post_launch:
      - target: branchB
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: branchB
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  docker Q:
    ready_wait: 10
    filename:
      ./stuff/DockerfileQ
    context_path: ./stuff
  branchCompose:
    pre_launch:
      - target: stuff-service
        command: exec
        options: "{target} bash -c 'ls -la ./'"
    post_launch:
      - target: stuff-service
        command: run
        options: "{target} bash -c 'echo test && echo test > test'"
    filename:
      ./docker-compose.yml
  nodocker:
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
