deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    ready_wait: 120
    backend_wait: 2
    depends_on:
      - docker-test/master
    depends_on_match_branch: true
  docker:
    vm_size: 1
    vm_storage_gb: 13
    depends_on:
      - nodockerfile/noconfig
    depends_on_match_branch: true
    ready_wait: 120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    run_options: --env TEST_VAL2=${SQUASH_BRANCH_WITH_ID} --restart always
    context_path: ./stuff
  dockerQ:
    ready_wait: 10
    filename:
      ./stuff/DockerfileQ
    context_path: ./stuff
  branchCompose:
    filename:
      ./docker-compose.yml
  nodocker:
    dockerimage:
      r.cfcr.io/wisedrette/wisedrette/dockertest:master
    docker_registry:
      server: r.cfcr.io
      username: wisedrette
      password: $REGISTRY_PASSWORD
