deployments:
  default:
    vm_size: 2G
    vm_storage_gb: 10G
    success_response_check:
      urls:
        - test--,/about/
        - test--,/
    subdomain_port_mapping:
      - test:3000
  no-fallback:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 180
    success_response_check:
      fallback: false
      url_check_behaviour: first_success
      urls:
        - test--,/about/
        - test--,/
    subdomain_port_mapping:
      - test:3000
  fallback-check-all:
    vm_size: 2G
    vm_storage_gb: 10G
    success_response_check:
      fallback: true
      url_check_behaviour: check_all
      urls:
        - test--,/about/
        - test--,/
    subdomain_port_mapping:
      - test:3000
  no-fallback-check-all:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 180
    success_response_check:
      fallback: false
      url_check_behaviour: check_all
      urls:
        - test--,/about/
        - test--,/
    subdomain_port_mapping:
      - test:3000
  no-fallback-check-all-err:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 180
    success_response_check:
      fallback: false
      url_check_behaviour: check_all
      urls:
        - test--,/about/
        - test--,/'
    subdomain_port_mapping:
      - test:3000
  fallback-check-all-err:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 180
    success_response_check:
      fallback: true
      url_check_behaviour: check_all
      urls:
        - test--,/about/
        - test--,/'
    subdomain_port_mapping:
      - test:3000
  no-fallback-err:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 180
    success_response_check:
      fallback: false
      urls:
        - test--,/'
    subdomain_port_mapping:
      - test:3000
