version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - APM_SECRET_TOKEN
      - APM_SERVER_URL
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_MASTER_DEPLOYMENT      
    command: bash ./run_server.sh
    volumes:
      - /assets:/assets
