version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - TEST_VAL
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_CHILD_DEPLOYMENT_DOCKER_TEST_DEPLOYMENT_DEPENDENCY
    command: bash ./run_server.sh
    volumes:
      - /assets:/assets
